name: API Tests CI

on:
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'  # Habilita cache para instalação mais rápida

      - name: Instalar dependências
        run: npm ci 

      - name: Configurar ambiente
        env:
          API_BASE_URL: ${{ vars.API_BASE_URL }}  
        run: |
          echo "API_BASE_URL=${API_BASE_URL}" > .env
          echo "Conteúdo do .env:"
          grep -o 'API_BASE_URL=[^ ]*' .env | sed 's/=.*/=***/'

      - name: Verificar conexão com a API
        run: |
          curl -I ${API_BASE_URL} || true  # Testa se a API está acessível

      - name: Executar testes
        run: npm test

      - name: Publicar relatório de testes
        if: always()  # Executa mesmo se os testes falharem
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/test-report.html